[workspace]
authors = ["zsiegel92 <zsiegel92@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "groupthere_mojo"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=26.3.0.dev2026031405,<27"
