// This file is auto-generated by @hey-api/openapi-ts

export { type Options, solveSolvePost } from './sdk.gen';
export type { ClientOptions, HttpValidationError, Party, Problem, Solution, SolveSolvePostData, SolveSolvePostError, SolveSolvePostErrors, SolveSolvePostResponse, SolveSolvePostResponses, Tripper, ValidationError } from './types.gen';
