// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { SolveSolvePostData, SolveSolvePostErrors, SolveSolvePostResponses } from './types.gen';
import { zSolveSolvePostData, zSolveSolvePostResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Solve
 */
export const solveSolvePost = <ThrowOnError extends boolean = false>(options: Options<SolveSolvePostData, ThrowOnError>) => (options.client ?? client).post<SolveSolvePostResponses, SolveSolvePostErrors, ThrowOnError>({
    requestValidator: async (data) => await zSolveSolvePostData.parseAsync(data),
    responseValidator: async (data) => await zSolveSolvePostResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/solve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
