// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://src` | (string & {});
};

/**
 * ExternalRideshareVehicle
 */
export type ExternalRideshareVehicle = {
    /**
     * Id
     */
    id: string;
    /**
     * Origin Id
     */
    origin_id: string;
    /**
     * Car Fits
     */
    car_fits?: number;
    /**
     * Cost Multiplier
     */
    cost_multiplier?: number;
    /**
     * Fixed Cost Seconds
     */
    fixed_cost_seconds?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Party
 */
export type Party = {
    /**
     * Id
     */
    id: string;
    /**
     * Vehicle Kind
     */
    vehicle_kind?: 'participant_vehicle' | 'external_rideshare';
    /**
     * Vehicle Id
     */
    vehicle_id?: string | null;
    /**
     * Driver Tripper Id
     */
    driver_tripper_id?: string | null;
    /**
     * External Rideshare Origin Id
     */
    external_rideshare_origin_id?: string | null;
    /**
     * Cost Multiplier
     */
    cost_multiplier?: number;
    /**
     * Passenger Tripper Ids
     */
    passenger_tripper_ids: Array<string>;
};

/**
 * Problem
 */
export type Problem = {
    /**
     * Id
     */
    id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Kind
     */
    kind?: 'shared_destination' | 'commute';
    /**
     * External Rideshare Mode
     */
    external_rideshare_mode?: 'disabled' | 'fallback' | 'always_available';
    /**
     * External Rideshare Seats
     */
    external_rideshare_seats?: number;
    /**
     * External Rideshare Cost Multiplier
     */
    external_rideshare_cost_multiplier?: number;
    /**
     * External Rideshare Fixed Cost Seconds
     */
    external_rideshare_fixed_cost_seconds?: number;
    /**
     * External Rideshare Vehicles
     */
    external_rideshare_vehicles?: Array<ExternalRideshareVehicle>;
    /**
     * Trippers
     */
    trippers: Array<Tripper>;
    /**
     * Tripper Distances
     *
     * Tuples of tripper_ids mapped to the distance in seconds between the tripper's origins
     */
    tripper_distances: Array<TripperDistance>;
};

/**
 * ProblemReceivedResponse
 */
export type ProblemReceivedResponse = {
    /**
     * Problem Id
     */
    problem_id: string;
    /**
     * Successfully Received
     */
    successfully_received: boolean;
};

/**
 * Solution
 */
export type Solution = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind?: 'shared_destination' | 'commute';
    /**
     * Successfully Completed
     */
    successfully_completed: boolean;
    /**
     * Feasible
     */
    feasible: boolean;
    /**
     * Optimal
     */
    optimal: boolean;
    /**
     * Parties
     */
    parties: Array<Party>;
    /**
     * Total Drive Seconds
     */
    total_drive_seconds: number;
    /**
     * External Rideshare Vehicle Count
     */
    external_rideshare_vehicle_count?: number;
    /**
     * Total External Rideshare Cost Seconds
     */
    total_external_rideshare_cost_seconds?: number;
    /**
     * Status Message
     */
    status_message?: string | null;
};

/**
 * Tripper
 */
export type Tripper = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Origin Id
     */
    origin_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Destination Id
     */
    destination_id?: string | null;
    /**
     * Required Arrival Time
     */
    required_arrival_time?: string | null;
    /**
     * Car Fits
     */
    car_fits: number;
    /**
     * Must Drive
     */
    must_drive: boolean;
    /**
     * Seconds Before Event Start Can Leave
     */
    seconds_before_event_start_can_leave: number;
    /**
     * Seconds Before Required Arrival Can Leave
     */
    seconds_before_required_arrival_can_leave?: number | null;
    /**
     * Distance To Destination Seconds
     */
    distance_to_destination_seconds: number;
};

/**
 * TripperDistance
 */
export type TripperDistance = {
    /**
     * Origin User Id
     */
    origin_user_id: string;
    /**
     * Destination User Id
     */
    destination_user_id: string;
    /**
     * Distance Seconds
     */
    distance_seconds: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SolveSolvePostData = {
    body: Problem;
    path?: never;
    query?: never;
    url: '/solve';
};

export type SolveSolvePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SolveSolvePostError = SolveSolvePostErrors[keyof SolveSolvePostErrors];

export type SolveSolvePostResponses = {
    /**
     * Successful Response
     */
    200: Solution;
};

export type SolveSolvePostResponse = SolveSolvePostResponses[keyof SolveSolvePostResponses];

export type SolveAsyncSolveAsyncPostData = {
    body: Problem;
    path?: never;
    query?: never;
    url: '/solve-async';
};

export type SolveAsyncSolveAsyncPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SolveAsyncSolveAsyncPostError = SolveAsyncSolveAsyncPostErrors[keyof SolveAsyncSolveAsyncPostErrors];

export type SolveAsyncSolveAsyncPostResponses = {
    /**
     * Successful Response
     */
    200: ProblemReceivedResponse;
};

export type SolveAsyncSolveAsyncPostResponse = SolveAsyncSolveAsyncPostResponses[keyof SolveAsyncSolveAsyncPostResponses];
