// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://src` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Party
 */
export type Party = {
    /**
     * Id
     */
    id: string;
    /**
     * Driver Tripper Id
     */
    driver_tripper_id?: string | null;
    /**
     * Passenger Tripper Ids
     */
    passenger_tripper_ids: Array<string>;
};

/**
 * Problem
 */
export type Problem = {
    /**
     * Id
     */
    id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Trippers
     */
    trippers: Array<Tripper>;
    /**
     * Tripper Origin Distances Seconds
     *
     * Tuples of tripper_ids mapped to the distance in seconds between the tripper's origins
     */
    tripper_origin_distances_seconds: {
        [key: string]: number;
    };
};

/**
 * ProblemReceivedResponse
 */
export type ProblemReceivedResponse = {
    /**
     * Problem Id
     */
    problem_id: string;
    /**
     * Successfully Received
     */
    successfully_received: boolean;
};

/**
 * Solution
 */
export type Solution = {
    /**
     * Id
     */
    id: string;
    /**
     * Parties
     */
    parties: Array<Party>;
    /**
     * Total Drive Seconds
     */
    total_drive_seconds: number;
};

/**
 * Tripper
 */
export type Tripper = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Origin Id
     */
    origin_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Car Fits
     */
    car_fits: number;
    /**
     * Seconds Before Event Start Can Leave
     */
    seconds_before_event_start_can_leave: number;
    /**
     * Distance To Destination Seconds
     */
    distance_to_destination_seconds: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SolveSolvePostData = {
    body: Problem;
    path?: never;
    query?: never;
    url: '/solve';
};

export type SolveSolvePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SolveSolvePostError = SolveSolvePostErrors[keyof SolveSolvePostErrors];

export type SolveSolvePostResponses = {
    /**
     * Successful Response
     */
    200: Solution;
};

export type SolveSolvePostResponse = SolveSolvePostResponses[keyof SolveSolvePostResponses];

export type SolveAsyncSolveAsyncPostData = {
    body: Problem;
    path?: never;
    query?: never;
    url: '/solve-async';
};

export type SolveAsyncSolveAsyncPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SolveAsyncSolveAsyncPostError = SolveAsyncSolveAsyncPostErrors[keyof SolveAsyncSolveAsyncPostErrors];

export type SolveAsyncSolveAsyncPostResponses = {
    /**
     * Successful Response
     */
    200: ProblemReceivedResponse;
};

export type SolveAsyncSolveAsyncPostResponse = SolveAsyncSolveAsyncPostResponses[keyof SolveAsyncSolveAsyncPostResponses];
