// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Party
 */
export const zParty = z.object({
    id: z.string(),
    driver_tripper_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    passenger_tripper_ids: z.array(z.string())
});

/**
 * ProblemReceivedResponse
 */
export const zProblemReceivedResponse = z.object({
    problem_id: z.string(),
    successfully_received: z.boolean()
});

/**
 * Solution
 */
export const zSolution = z.object({
    id: z.string(),
    parties: z.array(zParty),
    total_drive_seconds: z.number()
});

/**
 * Tripper
 */
export const zTripper = z.object({
    user_id: z.string(),
    origin_id: z.string(),
    event_id: z.string(),
    car_fits: z.int().gte(0).lte(5),
    must_drive: z.boolean(),
    seconds_before_event_start_can_leave: z.int().gte(0),
    distance_to_destination_seconds: z.number().gte(0)
});

/**
 * TripperDistance
 */
export const zTripperDistance = z.object({
    origin_user_id: z.string(),
    destination_user_id: z.string(),
    distance_seconds: z.number()
});

/**
 * Problem
 */
export const zProblem = z.object({
    id: z.string(),
    event_id: z.string(),
    trippers: z.array(zTripper),
    tripper_distances: z.array(zTripperDistance)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zSolveSolvePostData = z.object({
    body: zProblem,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zSolveSolvePostResponse = zSolution;

export const zSolveAsyncSolveAsyncPostData = z.object({
    body: zProblem,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zSolveAsyncSolveAsyncPostResponse = zProblemReceivedResponse;
