// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Party
 */
export const zParty = z.object({
    id: z.string(),
    driver_tripper_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    passenger_tripper_ids: z.array(z.string())
});

/**
 * Solution
 */
export const zSolution = z.object({
    id: z.string(),
    parties: z.array(zParty),
    total_drive_seconds: z.number()
});

/**
 * Tripper
 */
export const zTripper = z.object({
    id: z.string(),
    user_id: z.string(),
    origin_id: z.string(),
    event_id: z.string(),
    car_fits: z.int().gte(0).lte(5),
    seconds_before_event_start_can_leave: z.int().gte(0),
    distance_to_destination_seconds: z.number().gte(0)
});

/**
 * Problem
 */
export const zProblem = z.object({
    event_id: z.string(),
    trippers: z.array(zTripper),
    tripper_origin_distances_seconds: z.record(z.string(), z.number())
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zSolveSolvePostData = z.object({
    body: zProblem,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zSolveSolvePostResponse = zSolution;
